version: "3.7"
services:
  mysqldb-pet:
    image: mysql5.7
    ports: 
      - "3306:3306"
    volumes:
      - "mysqldb-pet:/var/lib/mysql"
    depends_on:
      - app-petclinic
    environment:
      - JENKINS_HOME=/var/jenk_home
      - HOME=/var/jenk_home 
      
  app-petclinic:
    image: manneyvictor/app-pet:acc
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb-pet
