version: '3'
services:
  petclinic-mysql:
    image: mysql:5.6
    environment:
     - MYSQL_ROOT_PASSWORD=petclinic
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
     - MYSQL_USER=petclinic
     - MYSQL_PASSWORD=petclinic
     - MYSQL_DATABASE=petclinic
    volumes:
     - "./data-petclinic:/var/lib/mysql"
    ports:
     - "3306:3306"
  petclinic:
    image: manneyvictor/petclinic:v1
    ports:
     - "80:8080"
    links:
     - petclinic-mysql
