version: "3.7"
services:
  jenkins:
    image: manneyvictor/jenkins:acc
    ports: 
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_HOME=/var/jenk_home
      - HOME=/var/jenk_home
    
  sonar:
    image: manneyvictor/sonar:acc
    ports: 
      - "9000:9000"
      - "9092:9092"
    depends_on:
    - jenkins
